### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by NelsonCarrillo** [reactmore/morelab#13]
Da error en:
Contraseña
Retype Password
Contraseña
Retype Password

Al presionar botón : Reset Password.

**Comment by reactmore** [comment]
Use English, if you mean reset password, you can't use it the first time because you have to adjust Email settings

**Comment by reactmore** [comment]
https://github.com/reactmore/morelab/blob/f8f53057f2c468364903ced5caf7d5578035ffbe/app/Database/Seeds/Development.php#L19

**Comment by NelsonCarrillo** [comment]
Hi reactmore

the error is in the img.
Password
Retype Password
(button)->Reset Password


![forgot password retype password](https://user-images.githubusercontent.com/50933641/156932216-7d8f167d-e7e0-4348-af57-c49f5bdfadb1.jpg)

![forgot password retype password - resetpassword](https://user-images.githubusercontent.com/50933641/156932229-386b51ea-c860-48b1-89e8-a38929c435fb.jpg)

Thanks

**Comment by reactmore** [comment]
Yes because root dir not in public

Pada tanggal Min, 6 Mar 2022 pukul 23.31 NelsonCarrillo <
***@***.***> menulis:

**Comment by reactmore** [comment]
![Untitled](https://user-images.githubusercontent.com/64960434/157024248-4ebc3e1a-34da-4d1a-99cd-e6fc842b45cc.png)
