### ISSUE TITLE
Call to undefined function App\Filters\get_general_settings() 

### ISSUE THREAD

**Issue by nyassuki** [reactmore/morelab#14]
Seems like helper not loaded to the baseController

**Comment by reactmore** [comment]
error when where? The helper is always loaded in the filter

**Comment by nyassuki** [comment]
<img width="1299" alt="Screenshot 2023-01-17 at 10 40 51" src="https://user-images.githubusercontent.com/77928925/212804994-a4eec4dd-a44d-4684-9097-6c9cbed9ab7b.png">

Maintenence.php 

at the begining, im trying to see deeper now

**Comment by nyassuki** [comment]
rename Custom_helper.php to custom_helper.php solve the problem
